name: ExLog
main: io.github.runassudo.exlog.ExLogPlugin
version: 0.0.4-alpha
author: RunasSudo

commands:
  exlog:
    aliases: el
    description: Execute an exLog command.
    usage: /<command> [command]
    permission: exlog.command
    permission-message: You don't have <permission>

permissions:
  exlog.*:
    description: Gives access to all exLog commands.
    default: op
    children:
      exlog.command: true
      exlog.command.*: true
      exlog.query.*: true
  exlog.command:
    description: Gives access to the main /exlog command.
    default: op
  exlog.command.*:
    description: Gives access to all /exlog subcommands.
    default: op
    children:
      exlog.command.query: true
  exlog.command.query:
    description: Gives access to the /exlog query subcommand.
    default: op
  exlog.query.*:
    description: Gives access to all exLog graphical query functions.
    default: op
    children:
      exlog.query.stick: true
      exlog.query.bone: true
  exlog.query.stick:
    description: Gives access to the exLog stick lookup.
    default: op
  exlog.query.bone:
    description: Gives access to the exLog bone lookup.
    default: op
